### ISSUE TITLE
Trying to output more than 1 table in a script results in an error

### ISSUE THREAD

**Issue by nemws1** [perlancar/perl-Text-ANSITable#4]
I've got the following script:

```
binmode(STDOUT, ":utf8");

use Text::ANSITable;

$table = new Text::ANSITable;
$table->border_style('UTF8::SingleLineCurved');
$table->columns(["hidden"]);
$table->add_row(["Test Row"]);
$table->show_header(0);
print $table->draw;
 
$table2 = new Text::ANSITable;
$table2->border_style('UTF8::SingleLineCurved');
$table2->columns(["hidden"]);
$table2->add_row(["Test Row"]);
$table2->show_header(0);
print $table2->draw;
```

The first table displays correctly, but the second table fails on the border_style call:

```
╭──────────╮
│ Test Row │
╰──────────╯
load_module_with_optional_args(): Failed to load module 'UTF8::SingleLineCurved' (all prefixes tried: BorderStyle) at /usr/local/share/perl5/site_perl/5.32/Module/Load/Util.pm line 71.

```

I've got quite a few scripts that generate multiple tables in a loop, and this is causing these scripts to bomb.  I can remove the *second* border_style call, but it should work since its operating on a different object instance.

Any thoughts/suggestions?

**Comment by nemws1** [comment]
Hmm.. so, before I was using Cygwin on a Windows box and getting the error I described.  Just tried the same script on my Mac (Catalina, 10.15.7) and Linux box (Ubuntu 20.04.2) and it works perfectly on both.  Tried on a *different* Windows box w/ Cygwin and it failed there again.  So, obviously a problem w/ Cygwin, and guessing more with Module::Load that Text::ANSITable.

**Comment by nemws1** [comment]
So, I mucked w/ Module::Load::Util to print out a better error than the die() command on line 71 and found that it was complaining about missing Text::ANSI::WidUtil:
```
╭──────────╮
│ Test Row │
╰──────────╯
Can't locate Text/ANSI/WideUtil.pm in @INC (you may need to install the Text::ANSI::WideUtil module) (@INC contains: /usr/local/lib/perl5/site_perl/5.32/x86_64-cygwin-threads /usr/local/share/perl5/site_perl/5.32 /usr/lib/perl5/vendor_perl/5.32/x86_64-cygwin-threads /usr/share/perl5/vendor_perl/5.32 /usr/lib/perl5/5.32/x86_64-cygwin-threads /usr/share/perl5/5.32) at /usr/local/share/perl5/site_perl/5.32/Text/ANSITable.pm line 298.

load_module_with_optional_args(): Failed to load module 'UTF8::SingleLineCurved' (all prefixes tried: BorderStyle) at /usr/local/share/perl5/site_perl/5.32/Module/Load/Util.pm line 72.

```

I've installed that module and now everything is working perfectly on Cygwin.

**Comment by perlancar** [comment]
Sorry for the late response, didn't see the notification.

Glad you resolved this issue. I'm closing it now.
