### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by poti1** [perlancar/perl-Text-ANSITable#8]
Looks like an interesting module. I was looking at the documentation, but I see that you're missing a README file (which shows documentation on GitHub). So I had to navigate to code -> lib -> Text.pm

**Comment by poti1** [comment]
Would you mind if I submit a PR with a README?

**Comment by poti1** [comment]
Clicked the close button by accident.

**Comment by poti1** [comment]
Ok cool. Not sure entirely how that works.
I see you have a dist.ini and I read that it means you're using Distzilla.

**Comment by perlancar** [comment]
Exactly. The README is generated by Dist::Zilla::Plugin::Pod2Readme.
